name: c
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  cloud_firestore: ^4.10.1
  geolocator: ^13.0.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11
  permission_handler: ^11.4.1
  shared_preferences: ^2.2.2
  excel: ^2.0.1
  image_picker: ^1.0.8
  http: ^1.1.0
  path_provider: ^2.1.2
  open_file: ^3.2.1
  uuid: ^4.2.1
  flutter_native_splash: ^2.3.1
  photo_view: ^0.15.0
  video_player: ^2.9.3
  chewie: ^1.10.0

dependency_overrides:
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#2C3E50"

flutter_native_splash:
  color: "#2C3E50"
  image: "assets/images/splash_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/icons/logo.png
